#!/bin/sh

BUILD=$1

if [ "$BUILD" != "debug" ] && [ "$BUILD" != "release" ]; then
  echo "usage ./deploy_osx.sh [debug | release] (package)"
  exit 1
fi

QT_VER=5.4.2
QTDIR=/usr/local/opt/qt-$QT_VER
APP_NAME=open_mp3_id3_tag
EXE_DIR=$BUILD/$APP_NAME.app/Contents/MacOS

$QTDIR/bin/lrelease mp3id3_encoding_conv.pro
cp ts/*.qm $EXE_DIR/
cp opencc/* $EXE_DIR/

cd $BUILD

cat ./$APP_NAME.app/Contents/Info.plist | \
sed 's/edu.cuhk.open_mp3_id3_tag/carlos.open_mp3_id3_tag/g' | \
sed 's/NOTE/CFBundleName/g' | \
sed 's/This file was generated by Qt\/QMake./Open MP3 ID3 Tag/g' > Info.plist
mv Info.plist ./$APP_NAME.app/Contents/Info.plist

# note -dmg will create a read-only image
$QTDIR/bin/macdeployqt $APP_NAME.app

if [ "$2" == "package" ]; then
  hdiutil create -size 100MB -fs HFS+ -volname "Open MP3 ID3 TAG" ./tmp.dmg
  hdiutil attach ./tmp.dmg
  cp -R ./$APP_NAME.app /Volumes/Open\ MP3\ ID3\ Tag/Open\ MP3\ ID3\ Tag.app
  ln -s /Applications /Volumes/Open\ MP3\ ID3\ Tag/
  diskutil eject /Volumes/Open\ MP3\ ID3\ Tag/
  hdiutil convert -format UDBZ -o ./$APP_NAME.dmg ./tmp.dmg
  rm ./tmp.dmg
fi

echo "done"