#!/bin/sh

BUILD=$1

if [ "$BUILD" == "" ]; then
  echo "usage ./deploy_osx.sh [build directory] (package)"
  exit 1
fi

QT_VER=5.9.7
QTDIR=/usr/local/opt/qt/$QT_VER
QTBIN=$QTDIR/clang_64/bin
APP_NAME=open_mp3_id3_tag
EXE_DIR=$BUILD/$APP_NAME.app/Contents/MacOS

$QTBIN/lrelease mp3id3_encoding_conv.pro
cp ts/*.qm $EXE_DIR/
cp opencc/* $EXE_DIR/

# cat ./$APP_NAME.app/Contents/Info.plist | \
# sed 's/NOTE/CFBundleName/g' | \
# sed 's/This file was generated by Qt\/QMake./Open MP3 ID3 Tag/g' > Info.plist
# mv Info.plist ./$APP_NAME.app/Contents/Info.plist

echo "$QTBIN/macdeployqt $BUILD/$APP_NAME.app"
$QTBIN/macdeployqt $BUILD/$APP_NAME.app
cp $(find ../OpenCC -name libopencc.2.dylib) $BUILD/$APP_NAME.app/Contents/Frameworks/
otool -L $BUILD/$APP_NAME.app/Contents/MacOS/open_mp3_id3_tag

if [ "$2" == "package" ]; then
  # note -dmg will create a read-only image
  hdiutil create -size 100MB -fs HFS+ -volname "Open MP3 ID3 TAG" ./tmp.dmg
  hdiutil attach ./tmp.dmg
  cp -R $BUILD/$APP_NAME.app /Volumes/Open\ MP3\ ID3\ Tag/Open\ MP3\ ID3\ Tag.app
  ln -s /Applications /Volumes/Open\ MP3\ ID3\ Tag/
  diskutil eject /Volumes/Open\ MP3\ ID3\ Tag/
  hdiutil convert -format UDBZ -o ./$APP_NAME.dmg ./tmp.dmg
  rm ./tmp.dmg
fi

echo "done"
